# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: math.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='math.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nmath.proto\"%\n\x0bIntegerPair\x12\n\n\x02i1\x18\x01 \x01(\x05\x12\n\n\x02i2\x18\x02 \x01(\x05\"\x14\n\x07Integer\x12\t\n\x01i\x18\x01 \x01(\x05\x32\'\n\x04Math\x12\x1f\n\x03\x61\x64\x64\x12\x0c.IntegerPair\x1a\x08.Integer\"\x00\x62\x06proto3'
)




_INTEGERPAIR = _descriptor.Descriptor(
  name='IntegerPair',
  full_name='IntegerPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='i1', full_name='IntegerPair.i1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='i2', full_name='IntegerPair.i2', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=51,
)


_INTEGER = _descriptor.Descriptor(
  name='Integer',
  full_name='Integer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='i', full_name='Integer.i', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=73,
)

DESCRIPTOR.message_types_by_name['IntegerPair'] = _INTEGERPAIR
DESCRIPTOR.message_types_by_name['Integer'] = _INTEGER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IntegerPair = _reflection.GeneratedProtocolMessageType('IntegerPair', (_message.Message,), {
  'DESCRIPTOR' : _INTEGERPAIR,
  '__module__' : 'math_pb2'
  # @@protoc_insertion_point(class_scope:IntegerPair)
  })
_sym_db.RegisterMessage(IntegerPair)

Integer = _reflection.GeneratedProtocolMessageType('Integer', (_message.Message,), {
  'DESCRIPTOR' : _INTEGER,
  '__module__' : 'math_pb2'
  # @@protoc_insertion_point(class_scope:Integer)
  })
_sym_db.RegisterMessage(Integer)



_MATH = _descriptor.ServiceDescriptor(
  name='Math',
  full_name='Math',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=75,
  serialized_end=114,
  methods=[
  _descriptor.MethodDescriptor(
    name='add',
    full_name='Math.add',
    index=0,
    containing_service=None,
    input_type=_INTEGERPAIR,
    output_type=_INTEGER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MATH)

DESCRIPTOR.services_by_name['Math'] = _MATH

# @@protoc_insertion_point(module_scope)
